#--------------------------Inspección de datos--------------------------
str(hotel_data)
hotel_data$hotel <- as.factor(hotel_data$hotel)
hotel_data$is_canceled <- as.factor(hotel_data$is_canceled)
hotel_data$market_segment <- as.factor(hotel_data$market_segment)
hotel_data$distribution_channel <- as.factor(hotel_data$distribution_channel)
hotel_data$is_repeated_guest <- as.factor(hotel_data$is_repeated_guest)
hotel_data$deposit_type <- as.factor(hotel_data$deposit_type)
hotel_data$customer_type <- as.factor(hotel_data$customer_type)
hotel_data$reservation_status <- as.factor(hotel_data$reservation_status)
hotel_data$reserved_room_type <- as.factor(hotel_data$reserved_room_type)
hotel_data$assigned_room_type <- as.factor(hotel_data$assigned_room_type)